package com.example.buffer.issue.replicate.abcdef

enum class AbcdefAppointmentType {
    ADDITIONAL_SERVICE,
    CANCEL_ADDITIONAL,
    CANCEL_INSTALL_NEW_CUSTOMER,
    CANCEL_MOVE,
    CANCEL_POOLTASK,
    CANCEL_REPAIR,
    EXTENDED_MOVE,
    INSTALL_NEW_CUSTOMER,
    POOLTASK,
    REPAIR,
    REPAIR_LEVEL_2,
    SIMPLE_INSTALLATION,
    SIMPLE_MOVE
}
